 <?php
 // module/Subscriber/view/subscriber/subscriber/edit.phtml:

 $title = 'View Subscriber';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'subscriber',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo '<div class="form-group">';
 echo $this->formRow($form->get('username')->setAttribute('class', 'form-control'));
 echo '</div>';
 echo '<div class="form-group">';
 echo $this->formRow($form->get('email')->setAttribute('class', 'form-control'));
 echo '</div>';
 echo '<div class="form-group">';
 echo $this->formRow($form->get('password')->setAttribute('class', 'form-control'));
 echo '</div>';
 echo '<div class="form-group">';
 echo $this->formRow($form->get('product_id')->setAttribute('class', 'form-control'));
 echo '</div>';
 echo '<a class="btn btn-default" href="'.$this->url('subscriber').'">Back</a>';
 echo $this->form()->closeTag();